### ISSUE TITLE
Missing Licenses

### ISSUE THREAD

**Issue by NotAKidoS** [Perkedel/CVR_Stuffings#2]
Hi, I stumbled on your repo and saw a few of my packages happened to be hosted here:

- AASEmulator
- SimpleAAS
- Avatar Scale Tool
- CCK.BaseAnimatorPatch
- Quick Material Swap
- Avatar Pointer Generator
- Wall Walker Prefab

I would like to notify you that *some* of the above listed packages do not include the MIT License in their package directly, and as such are missing from this repo. **You are completely fine to host the packages if you so please**, but I would greatly appreciate if the proper licenses were attached.

—

On another note- The following packages of mine are also included, **both of which are not released publicly**, and as such are not meant for redistribution:

- [Roblox Path Giver](https://github.com/Perkedel/CVR_Stuffings/tree/main/DiceGlow/Assets/_Roblox%20Path%20Giver)
- [CCK.GestureToInt](https://github.com/Perkedel/CVR_Stuffings/tree/main/DiceGlow/Assets/CCK.GestureToInt)

I would appreciate if those two packages could be removed, at least until I decide to publicly host them myself somewhere in the future.

Just to state: no hard feelings about any of this by the way. It's not an immediate issue so feel free to take your time with it. Just wanted to bring it to your attention.

Thank you for your understanding and cooperation.

**Comment by JOELwindows7** [comment]
## Response received
Thank you for your time in notifying us for this issue. We have handled your request

## License file
License files are now have been attached to each of those assets, alongside with the Readme files for each respective assets.  
You may as well would like to copy over these files inside the `.unitypackage` files next time.

## Not public yet files
These files have now been removed & purged from history. Future commits will **ignore those files until your desired publication tbd**. Until that time, 2 directory has been added to our `.gitignore` file. Feel free to let us know if one or both has now been ready for public.

For reference, these files were found on Creator Showcase, and it was stated that you requested Kavex to upload some of your files on your behalf, stated [here](https://discord.com/channels/1092233134566801478/1092233135925760013/1096498197213491231) on 15th April 2023.

## End
You're welcome.

If you have any further questions, let us know.
